# Generated by Django 4.2.3 on 2023-09-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='image',
        ),
    ]
