# Generated by Django 4.2.3 on 2023-09-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerceApp', '0002_rename_img_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='img',
            new_name='image',
        ),
    ]
